import type { ProductCountry, ProductDimension, ProductMarketItem, ProductTodayResponse } from "../../types/product";
import { Badge, DetailsDisclosure, Panel, Sparkline } from "../../components/Primitives";
import { ConceptStrip } from "../../components/ConceptHelp";

const directionLabel: Record<string, string> = { up: "上行", down: "下行", flat: "持平", mixed: "分化", strong: "偏强", weak: "偏弱", unavailable: "缺失" };
const countryStatusLabel: Record<string, string> = { available: "可用", partial: "部分覆盖", stale: "数据较旧", missing: "缺失" };
const eventStatusLabel: Record<string, string> = { scheduled: "待公布", released: "已公布", partial: "部分数据", blocked: "受限" };

function DimensionTile({ item, onOpen }: { item: ProductDimension; onOpen: () => void }) {
  const state = directionLabel[item.direction] ?? item.direction;
  return <button type="button" class="metric-tile metric-tile--state" onClick={onOpen}><span class="metric-tile__label">{item.label}</span><strong class="metric-tile__value">{state}</strong><span class="metric-tile__meta">指数 {item.score == null ? "—" : item.score.toFixed(2)} · 置信 {Math.round(item.confidence * 100)}%</span></button>;
}

function MarketRow({ item, onOpen }: { item: ProductMarketItem; onOpen: () => void }) {
  const direction = item.direction === "up" ? "up" : item.direction === "down" ? "down" : "neutral";
  return <tr class="market-row" onClick={onOpen}><td><div class="market-row__name"><strong>{item.label}</strong></div></td><td class="market-row__value">{item.formatted_value}</td><td><span class={`market-row__change ${direction === "up" ? "positive" : direction === "down" ? "negative" : ""}`}>{item.change == null ? "—" : `${item.change > 0 ? "+" : ""}${item.change.toFixed(2)} ${item.change_unit}`}</span></td><td><Sparkline values={item.sparkline} tone={direction} /></td><td>{item.status !== "available" || item.freshness !== "AVAILABLE" ? <span class={`status-dot status-dot--${item.status}`}>{item.status === "missing" ? "缺失" : item.freshness === "STALE" ? "较旧" : item.freshness}</span> : null}</td></tr>;
}

function GlobalCompact({ countries, onOpen }: { countries: ProductCountry[]; onOpen: (country: ProductCountry) => void }) {
  return <div class="board-grid board-grid--markets">{countries.map((country) => <button type="button" class="metric-tile" key={country.key} onClick={() => onOpen(country)}><span class="metric-tile__label">{country.label}</span><strong class="metric-tile__value metric-tile__value--compact">{country.available_dimensions.length ? country.available_dimensions.slice(0, 2).map((key) => country.dimensions[key]?.label ?? key).join(" / ") : "暂无数据"}</strong><span class="metric-tile__meta"><span>{countryStatusLabel[country.status] ?? country.status}</span></span></button>)}</div>;
}

export function TodayBoard({ data, learningMode, onOpenDimension, onOpenMarket, onOpenCountry, onOpenEvent }: { data: ProductTodayResponse; learningMode: boolean; onOpenDimension: (item: ProductDimension) => void; onOpenMarket: (item: ProductMarketItem) => void; onOpenCountry: (item: ProductCountry) => void; onOpenEvent: (id: string) => void }) {
  return <div class="workspace workspace--product workspace--today"><section class="page-heading page-heading--compact"><div><div class="eyebrow">TODAY / {new Date(data.as_of).toLocaleDateString()}</div><h1>今日环境</h1><p>当前宏观状态、变化最大的方向、主要市场与接下来要关注的事件。</p><ConceptStrip concepts={["growth", "inflation", "liquidity", "policy_tightness"]} active={learningMode} /></div><div class="page-heading__aside"><span class="muted">更新于 {new Date(data.as_of).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</span></div></section>
    <div class="product-grid"><Panel title="宏观状态" eyebrow="STATE"><div class="board-grid">{data.macro_snapshot.slice(0, 8).map((item) => <DimensionTile item={item} key={item.key} onOpen={() => onOpenDimension(item)} />)}</div></Panel><Panel title="变化焦点" eyebrow="FOCUS"><div class="focus-list">{data.what_changed.slice(0, 4).map((change, index) => { const dimension = data.macro_snapshot.find((item) => item.key === change.category) ?? data.macro_snapshot[index % Math.max(1, data.macro_snapshot.length)]; return <button type="button" class="change-list__row" key={`${change.category}-${change.what}`} onClick={() => dimension && onOpenDimension(dimension)}><span class="change-list__dot" /><span><strong>{change.what}</strong><small>{change.why}</small></span></button>; })}{!data.what_changed.length ? <div class="empty-action"><div><h3>暂未识别出显著变化</h3><p>同步或刷新真实数据后重新排序。</p></div></div> : null}</div></Panel></div>
    <Panel title="主要市场" eyebrow="CROSS-ASSET" aside={<span class="muted">最近有效交易日</span>}><div class="table-wrap"><table class="market-board"><thead><tr><th>资产</th><th>最新</th><th>1日</th><th>趋势</th><th></th></tr></thead><tbody>{data.markets.slice(0, 8).map((item) => <MarketRow item={item} key={item.key} onOpen={() => onOpenMarket(item)} />)}</tbody></table></div>{!data.markets.length ? <div class="empty-action"><div><h3>暂无日线市场数据</h3><p>同步或导入真实市场数据后即可启用。</p></div></div> : null}</Panel>
    <div class="product-grid"><Panel title="全球状态" eyebrow="COUNTRIES"><GlobalCompact countries={data.global} onOpen={onOpenCountry} /></Panel><Panel title="接下来" eyebrow="EVENTS"><div class="event-list">{data.upcoming.slice(0, 5).map((event) => <button type="button" class="event-list__row" key={event.id} onClick={() => onOpenEvent(event.id)}><span class="event-list__date">{new Date(event.scheduled_at).toLocaleDateString(undefined, { month: "short", day: "numeric" })}</span><span><strong>{event.title}</strong><small>{event.release_type} / {event.period_label}</small></span><span class="muted">{eventStatusLabel[event.status] ?? event.status}</span></button>)}</div></Panel></div>
    <Panel title="最新研究" eyebrow="REPLAY"><div class="research-feed">{data.latest_research.length ? data.latest_research.map((item) => <button type="button" class="research-row" key={item.id} onClick={() => onOpenEvent(item.id)}><div><span class="row-meta">{item.release_type} / {item.period_label}</span><strong>{item.title}</strong></div><Badge tone={item.data_mode === "fixture" ? "warn" : "good"}>{item.classification ?? "已完成"}</Badge></button>) : <div class="empty-action"><div><h3>尚无已完成的真实研究</h3><p>需要 Actual、T0 前 Consensus 和可用的市场数据。</p></div></div>}</div></Panel>
    {learningMode ? <Panel title="如何阅读" eyebrow="LEARNING"><p class="learning-note">宏观状态描述环境，市场行描述价格反应。方向不代表好坏，也不等于唯一原因。</p><DetailsDisclosure label="数据边界"><p class="learning-note">缺失值不会被估算。打开“数据详情”可以查看来源、时效与能力限制。</p></DetailsDisclosure></Panel> : null}
  </div>;
}
