"""Canonical instruments used by event-window analysis."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class InstrumentDefinition:
    key: str
    symbol: str
    title: str
    asset_class: str
    instrument_type: str
    exchange: str | None
    quote_unit: str
    measurement_type: str
    timezone: str
    is_proxy: bool = False
    proxy_for: str | None = None
    is_derived: bool = False
    input_datasets: tuple[str, ...] = ()
    formula: str | None = None
    calculation_version: str | None = None


INSTRUMENTS: tuple[InstrumentDefinition, ...] = (
    InstrumentDefinition(
        "gold_gc",
        "GC",
        "黄金期货",
        "metals",
        "futures",
        "COMEX",
        "USD/troy ounce",
        "price",
        "America/Chicago",
    ),
    InstrumentDefinition(
        "silver_si",
        "SI",
        "白银期货",
        "metals",
        "futures",
        "COMEX",
        "USD/troy ounce",
        "price",
        "America/Chicago",
    ),
    InstrumentDefinition(
        "wti_cl",
        "CL",
        "WTI 原油期货",
        "energy",
        "futures",
        "NYMEX",
        "USD/barrel",
        "price",
        "America/Chicago",
    ),
    InstrumentDefinition(
        "sp500_es",
        "ES",
        "标普500指数期货",
        "equity_index",
        "futures",
        "CME",
        "index points",
        "price",
        "America/Chicago",
    ),
    InstrumentDefinition(
        "nasdaq_nq",
        "NQ",
        "纳斯达克100指数期货",
        "equity_index",
        "futures",
        "CME",
        "index points",
        "price",
        "America/Chicago",
    ),
    InstrumentDefinition(
        "ust2y_zt",
        "ZT",
        "2年期美债期货（收益率代理）",
        "rates",
        "futures_proxy",
        "CBOT",
        "price points",
        "yield_proxy_futures_price",
        "America/Chicago",
        True,
        "美国2年期国债收益率分钟变化",
    ),
    InstrumentDefinition(
        "ust10y_zn",
        "ZN",
        "10年期美债期货（收益率代理）",
        "rates",
        "futures_proxy",
        "CBOT",
        "price points",
        "yield_proxy_futures_price",
        "America/Chicago",
        True,
        "美国10年期国债收益率分钟变化",
    ),
    InstrumentDefinition(
        "dollar_dxy",
        "DX",
        "美元指数期货",
        "fx",
        "futures",
        "ICE Futures US",
        "index points",
        "price",
        "America/New_York",
    ),
    InstrumentDefinition(
        "eurusd", "EURUSD", "EUR/USD", "fx", "spot", None, "USD per EUR", "price", "UTC"
    ),
    InstrumentDefinition(
        "usdjpy", "USDJPY", "USD/JPY", "fx", "spot", None, "JPY per USD", "price", "UTC"
    ),
    InstrumentDefinition(
        "vix",
        "VX",
        "VIX 波动率期货",
        "volatility",
        "futures",
        "Cboe Futures Exchange",
        "index points",
        "price",
        "America/Chicago",
    ),
    # Public daily context instruments are deliberately separate from the
    # futures/event instruments above.  FRED observations for these keys are
    # not eligible for minute event windows or futures settlement claims.
    InstrumentDefinition(
        "sp500_cash",
        "SP500",
        "S&P 500 cash index (context)",
        "equity_index",
        "index_context",
        None,
        "index points",
        "price_context",
        "America/New_York",
    ),
    InstrumentDefinition(
        "vix_cash",
        "VIX",
        "VIX cash index (context)",
        "volatility",
        "index_context",
        None,
        "index points",
        "price_context",
        "America/New_York",
    ),
    InstrumentDefinition(
        "wti_spot",
        "WTI",
        "WTI spot reference (context)",
        "energy",
        "spot_context",
        None,
        "USD/barrel",
        "price_context",
        "UTC",
    ),
    InstrumentDefinition(
        "brent_spot",
        "BRENT",
        "Brent spot reference (context)",
        "energy",
        "spot_context",
        None,
        "USD/barrel",
        "price_context",
        "UTC",
    ),
    InstrumentDefinition(
        "dollar_broad_context",
        "BROAD_USD",
        "Broad U.S. dollar index (context)",
        "fx",
        "index_context",
        None,
        "index points",
        "price_context",
        "America/New_York",
    ),
    InstrumentDefinition(
        "ust2y_yield_context",
        "DGS2",
        "U.S. 2-year Treasury yield (context)",
        "rates",
        "yield_context",
        None,
        "percent",
        "yield",
        "America/New_York",
    ),
    InstrumentDefinition(
        "ust10y_yield_context",
        "DGS10",
        "U.S. 10-year Treasury yield (context)",
        "rates",
        "yield_context",
        None,
        "percent",
        "yield",
        "America/New_York",
    ),
    InstrumentDefinition(
        "ust3m_yield_context",
        "DGS3MO",
        "U.S. 3-month Treasury yield (context)",
        "rates",
        "yield_context",
        None,
        "percent",
        "yield",
        "America/New_York",
    ),
    InstrumentDefinition(
        "ust5y_yield_context",
        "DGS5",
        "U.S. 5-year Treasury yield (context)",
        "rates",
        "yield_context",
        None,
        "percent",
        "yield",
        "America/New_York",
    ),
    InstrumentDefinition(
        "ust30y_yield_context",
        "DGS30",
        "U.S. 30-year Treasury yield (context)",
        "rates",
        "yield_context",
        None,
        "percent",
        "yield",
        "America/New_York",
    ),
    InstrumentDefinition(
        "ust10y_real_yield_context",
        "DFII10",
        "U.S. 10-year real yield (context)",
        "rates",
        "yield_context",
        None,
        "percent",
        "yield",
        "America/New_York",
    ),
    InstrumentDefinition(
        "nasdaq100_cash",
        "NASDAQ100",
        "Nasdaq-100 cash index (context)",
        "equity_index",
        "index_context",
        None,
        "index points",
        "price_context",
        "America/New_York",
    ),
    InstrumentDefinition(
        "eurusd_context",
        "DEXUSEU",
        "EUR/USD reference rate (context)",
        "fx",
        "spot_context",
        None,
        "USD per EUR",
        "price_context",
        "America/New_York",
    ),
    InstrumentDefinition(
        "usdjpy_context",
        "DEXJPUS",
        "USD/JPY reference rate (context)",
        "fx",
        "spot_context",
        None,
        "JPY per USD",
        "price_context",
        "America/New_York",
    ),
    InstrumentDefinition(
        "usdcny_context",
        "DEXCHUS",
        "USD/CNY reference rate (context)",
        "fx",
        "spot_context",
        None,
        "CNY per USD",
        "price_context",
        "America/New_York",
    ),
    InstrumentDefinition(
        "hy_spread_context",
        "BAMLH0A0HYM2",
        "U.S. high-yield spread (context)",
        "credit",
        "spread_context",
        None,
        "percent",
        "spread",
        "America/New_York",
    ),
    InstrumentDefinition(
        key="curve_2s10s_derived",
        symbol="2S10S",
        title="U.S. 2s10s Treasury curve",
        asset_class="rates",
        instrument_type="derived_spread",
        exchange=None,
        quote_unit="percent",
        measurement_type="spread",
        timezone="America/New_York",
        is_derived=True,
        input_datasets=("ust10y_yield_context", "ust2y_yield_context"),
        formula="US10Y - US2Y",
        calculation_version="market-derived-v1",
    ),
    InstrumentDefinition(
        key="curve_3m10y_derived",
        symbol="3M10Y",
        title="U.S. 3m10y Treasury curve",
        asset_class="rates",
        instrument_type="derived_spread",
        exchange=None,
        quote_unit="percent",
        measurement_type="spread",
        timezone="America/New_York",
        is_derived=True,
        input_datasets=("ust10y_yield_context", "ust3m_yield_context"),
        formula="US10Y - US3M",
        calculation_version="market-derived-v1",
    ),
)

INSTRUMENT_BY_KEY = {item.key: item for item in INSTRUMENTS}
